"""update db

Revision ID: 229b0c65144b
Revises: e688748bd992
Create Date: 2022-05-20 10:52:43.395624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '229b0c65144b'
down_revision = 'e688748bd992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_categories',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_categories_created_at'), 'db_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_categories_deleted'), 'db_categories', ['deleted'], unique=False)
    op.create_index(op.f('ix_db_categories_name'), 'db_categories', ['name'], unique=False)
    op.create_table('db_discount',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('discount', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_discount_code'), 'db_discount', ['code'], unique=False)
    op.create_index(op.f('ix_db_discount_created_at'), 'db_discount', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_discount_deleted'), 'db_discount', ['deleted'], unique=False)
    op.create_index(op.f('ix_db_discount_discount'), 'db_discount', ['discount'], unique=False)
    op.create_table('db_order',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('sum_price', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['db_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_order_created_at'), 'db_order', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_order_deleted'), 'db_order', ['deleted'], unique=False)
    op.create_index(op.f('ix_db_order_sum_price'), 'db_order', ['sum_price'], unique=False)
    op.create_table('db_product',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['db_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_product_created_at'), 'db_product', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_product_deleted'), 'db_product', ['deleted'], unique=False)
    op.create_index(op.f('ix_db_product_name'), 'db_product', ['name'], unique=False)
    op.create_index(op.f('ix_db_product_price'), 'db_product', ['price'], unique=False)
    op.create_index(op.f('ix_db_product_quantity'), 'db_product', ['quantity'], unique=False)
    op.create_table('db_cart',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['db_product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['db_user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.create_index(op.f('ix_db_cart_created_at'), 'db_cart', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_cart_deleted'), 'db_cart', ['deleted'], unique=False)
    op.create_table('db_order_detail',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['db_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['db_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_order_detail_created_at'), 'db_order_detail', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_order_detail_deleted'), 'db_order_detail', ['deleted'], unique=False)
    op.create_table('db_product_discount',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('discount_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['db_discount.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['db_product.id'], ),
    sa.PrimaryKeyConstraint('id', 'product_id', 'discount_id')
    )
    op.create_index(op.f('ix_db_product_discount_created_at'), 'db_product_discount', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_product_discount_deleted'), 'db_product_discount', ['deleted'], unique=False)
    op.drop_index('ix_db_item_created_at', table_name='db_item')
    op.drop_index('ix_db_item_deleted', table_name='db_item')
    op.drop_index('ix_db_item_description', table_name='db_item')
    op.drop_index('ix_db_item_title', table_name='db_item')
    op.drop_table('db_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_item',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='db_item_pkey')
    )
    op.create_index('ix_db_item_title', 'db_item', ['title'], unique=False)
    op.create_index('ix_db_item_description', 'db_item', ['description'], unique=False)
    op.create_index('ix_db_item_deleted', 'db_item', ['deleted'], unique=False)
    op.create_index('ix_db_item_created_at', 'db_item', ['created_at'], unique=False)
    op.drop_index(op.f('ix_db_product_discount_deleted'), table_name='db_product_discount')
    op.drop_index(op.f('ix_db_product_discount_created_at'), table_name='db_product_discount')
    op.drop_table('db_product_discount')
    op.drop_index(op.f('ix_db_order_detail_deleted'), table_name='db_order_detail')
    op.drop_index(op.f('ix_db_order_detail_created_at'), table_name='db_order_detail')
    op.drop_table('db_order_detail')
    op.drop_index(op.f('ix_db_cart_deleted'), table_name='db_cart')
    op.drop_index(op.f('ix_db_cart_created_at'), table_name='db_cart')
    op.drop_table('db_cart')
    op.drop_index(op.f('ix_db_product_quantity'), table_name='db_product')
    op.drop_index(op.f('ix_db_product_price'), table_name='db_product')
    op.drop_index(op.f('ix_db_product_name'), table_name='db_product')
    op.drop_index(op.f('ix_db_product_deleted'), table_name='db_product')
    op.drop_index(op.f('ix_db_product_created_at'), table_name='db_product')
    op.drop_table('db_product')
    op.drop_index(op.f('ix_db_order_sum_price'), table_name='db_order')
    op.drop_index(op.f('ix_db_order_deleted'), table_name='db_order')
    op.drop_index(op.f('ix_db_order_created_at'), table_name='db_order')
    op.drop_table('db_order')
    op.drop_index(op.f('ix_db_discount_discount'), table_name='db_discount')
    op.drop_index(op.f('ix_db_discount_deleted'), table_name='db_discount')
    op.drop_index(op.f('ix_db_discount_created_at'), table_name='db_discount')
    op.drop_index(op.f('ix_db_discount_code'), table_name='db_discount')
    op.drop_table('db_discount')
    op.drop_index(op.f('ix_db_categories_name'), table_name='db_categories')
    op.drop_index(op.f('ix_db_categories_deleted'), table_name='db_categories')
    op.drop_index(op.f('ix_db_categories_created_at'), table_name='db_categories')
    op.drop_table('db_categories')
    # ### end Alembic commands ###
