"""update db

Revision ID: 3376532a98bd
Revises: 4ef9b87111ea
Create Date: 2022-05-20 14:35:35.505571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3376532a98bd'
down_revision = '4ef9b87111ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('db_product_category_id_fkey', 'db_product', type_='foreignkey')
    op.drop_column('db_product', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_product', sa.Column('category_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('db_product_category_id_fkey', 'db_product', 'db_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
