"""update db

Revision ID: 3ab0a0f328a7
Revises: e4f767e41e93
Create Date: 2022-05-23 20:27:07.640997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ab0a0f328a7'
down_revision = 'e4f767e41e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('db_cart', 'product_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('db_cart', 'product_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
