"""update db

Revision ID: 4bec5f4a733e
Revises: d6b99e487cef
Create Date: 2022-05-25 03:13:25.984042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bec5f4a733e'
down_revision = 'd6b99e487cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_cart',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('discount_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('sum_price', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['discount_id'], ['db_discount.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['db_product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['db_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_cart_created_at'), 'db_cart', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_cart_deleted'), 'db_cart', ['deleted'], unique=False)
    op.create_index(op.f('ix_db_cart_quantity'), 'db_cart', ['quantity'], unique=False)
    op.create_index(op.f('ix_db_cart_sum_price'), 'db_cart', ['sum_price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_cart_sum_price'), table_name='db_cart')
    op.drop_index(op.f('ix_db_cart_quantity'), table_name='db_cart')
    op.drop_index(op.f('ix_db_cart_deleted'), table_name='db_cart')
    op.drop_index(op.f('ix_db_cart_created_at'), table_name='db_cart')
    op.drop_table('db_cart')
    # ### end Alembic commands ###
