"""update db

Revision ID: 4ef9b87111ea
Revises: d82ec9568489
Create Date: 2022-05-20 11:53:09.945978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ef9b87111ea'
down_revision = 'd82ec9568489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_product_categories',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['db_categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['db_product.id'], ),
    sa.PrimaryKeyConstraint('id', 'product_id', 'category_id')
    )
    op.create_index(op.f('ix_db_product_categories_created_at'), 'db_product_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_product_categories_deleted'), 'db_product_categories', ['deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_product_categories_deleted'), table_name='db_product_categories')
    op.drop_index(op.f('ix_db_product_categories_created_at'), table_name='db_product_categories')
    op.drop_table('db_product_categories')
    # ### end Alembic commands ###
