"""update db

Revision ID: 590cdc6d10b9
Revises: 4bec5f4a733e
Create Date: 2022-05-25 14:45:51.741726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '590cdc6d10b9'
down_revision = '4bec5f4a733e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_order_detail', sa.Column('discount_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'db_order_detail', 'db_discount', ['discount_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'db_order_detail', type_='foreignkey')
    op.drop_column('db_order_detail', 'discount_id')
    # ### end Alembic commands ###
