"""update db

Revision ID: 661da533eadf
Revises: cd43ff64f33d
Create Date: 2022-05-23 17:38:07.511372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661da533eadf'
down_revision = 'cd43ff64f33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
