"""update db

Revision ID: 7dc120738750
Revises: 590cdc6d10b9
Create Date: 2022-05-25 14:54:51.077663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc120738750'
down_revision = '590cdc6d10b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
