"""update db

Revision ID: 9e3ed070d2b0
Revises: 229b0c65144b
Create Date: 2022-05-20 11:02:59.189817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3ed070d2b0'
down_revision = '229b0c65144b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_categories', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_categories', 'is_active')
    # ### end Alembic commands ###
