"""update db

Revision ID: b4202de563a8
Revises: cf8dea7f5939
Create Date: 2022-05-23 17:23:38.235782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4202de563a8'
down_revision = 'cf8dea7f5939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_cart', sa.Column('discount_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'db_cart', 'db_discount', ['discount_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'db_cart', type_='foreignkey')
    op.drop_column('db_cart', 'discount_id')
    # ### end Alembic commands ###
