"""update db

Revision ID: cd43ff64f33d
Revises: b4202de563a8
Create Date: 2022-05-23 17:36:18.212911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd43ff64f33d'
down_revision = 'b4202de563a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
