"""update db

Revision ID: cf8dea7f5939
Revises: 3376532a98bd
Create Date: 2022-05-20 14:45:18.542558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8dea7f5939'
down_revision = '3376532a98bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
