"""update db

Revision ID: d82ec9568489
Revises: f3178ca37e29
Create Date: 2022-05-20 11:45:49.785054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82ec9568489'
down_revision = 'f3178ca37e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
