"""update db

Revision ID: d884e3a702af
Revises: 661da533eadf
Create Date: 2022-05-23 17:39:00.844075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd884e3a702af'
down_revision = '661da533eadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
