"""update db

Revision ID: e688748bd992
Revises: c4157919bfa1
Create Date: 2022-05-20 10:27:27.664875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e688748bd992'
down_revision = 'c4157919bfa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
