"""update db

Revision ID: f3178ca37e29
Revises: f25156444143
Create Date: 2022-05-20 11:42:36.899200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3178ca37e29'
down_revision = 'f25156444143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
